# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: R-CMD-check

on:
  push:
    branches:
      - devel
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions: read-all

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest, r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest, r: 'release'}
          - {os: ubuntu-latest, r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache: always
          extra-packages: any::rcmdcheck any::igraph any::scRNAseq any::SummarizedExperiment
          needs: check

      - name: Install macOS system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install libtool

      - name: Install Windows system dependencies
        if: runner.os == 'Windows'
        shell: bash
        run: |
          pacman -S mingw-w64-x86_64-toolchain --noconfirm
          pacman -S mingw-w64-x86_64-make --noconfirm

      - name: Install Linux system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update && sudo apt upgrade
          sudo apt install gcc

      - name: Clone igraph
        shell: bash
        run: |
          cd src/se2
          git submodule init
          git submodule update --recursive

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          build_args: 'c("--no-manual","--compact-vignettes=gs+qpdf")'
          error-on: '"error"'
